---
x-database-common:
  &database-env
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PORT: ${POSTGRES_PORT}


services:
  api:
    volumes:
      - storage:/app/uploads

  database:
    environment:
      <<: *database-env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - database-volume:/var/lib/postgresql/data

volumes:
  storage:
