ARG DOCKER_IMAGE=python:3.12-slim

FROM $DOCKER_IMAGE

ENV PROJECT_DIR=/workspace

WORKDIR /workspace

COPY alembic.ini pyproject.toml ${PROJECT_DIR}

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -U setuptools wheel \
    && pip install --no-cache-dir -U .

COPY app/db ${PROJECT_DIR}/app/db
COPY app/alembic ${PROJECT_DIR}/app/alembic
