---
x-database-common:
  &database-env
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_PORT: ${POSTGRES_PORT}


services:
  quantee-api:
    build:
      context: .
      dockerfile: Dockerfile_api
    environment:
        <<: *database-env
    volumes:
      - storage:/storage

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - quantee-api


#  database:
#    environment:
#      <<: *database-env
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - database-volume:/var/lib/postgresql/data

volumes:
  storage:
