services:
  quantee-api:
    build:
      context: .
      dockerfile: Dockerfile_api
    env_file: ".env"
    environment:
        STORAGE_DIR: ${STORAGE_ROOT_DIR}
    volumes:
      - storage:/storage

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - quantee-api

  database:
    image: postgres:latest
    env_file: ".env"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile_migrations
    env_file: ".env"
    environment:
      POSTGRES_HOST: database
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
    entrypoint: ["alembic", "upgrade", "head"]

volumes:
  postgres-db-volume:
  storage:

networks:
  app-network:
    driver: bridge
