ARG DOCKER_IMAGE=python:3.12-slim

FROM $DOCKER_IMAGE AS builder

ENV PROJECT_DIR=/workspace/project

COPY ./README.md ./pyproject.toml ${PROJECT_DIR}/
COPY ./app ${PROJECT_DIR}/app/

WORKDIR ${PROJECT_DIR}
RUN pip install --no-cache-dir build && python -m build --wheel

FROM $DOCKER_IMAGE

ENV PROJECT_DIR=/workspace/project
RUN mkdir -p ${PROJECT_DIR}

WORKDIR ${PROJECT_DIR}

COPY --from=builder ${PROJECT_DIR}/dist/*.whl ${PROJECT_DIR}
RUN pip install --no-cache-dir ${PROJECT_DIR}/*.whl \
    && rm ${PROJECT_DIR}/*.whl
COPY --from=builder ${PROJECT_DIR}/app/api/gunicorn_config.py ${PROJECT_DIR}/gunicorn_config.py

CMD ["sh", "-c", "python -m gunicorn --log-level INFO --timeout 600 -c ${PROJECT_DIR}/gunicorn_config.py app.api.main:app"]
